version: "3.3"
services:
    backend:
        container_name: wind-turbine
        image: wind-turbine
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '80:8000'
        volumes:
            - ./app:/wind-turbine/app
