version: "3.3"
services:
    backend:
        container_name: wind-turbine
        image: wind-turbine
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '80:8000'
        volumes:
            - ./app:/wind-turbine/app
    mongo:
        image: mongo:6.0-focal
        restart: always
        ports:
        - 27017:27017
        volumes:
        - ./mongo_data:/data/db
        env_file:
        - ./.env
        command: --quiet
