from environs import Env

env = Env()
env.read_env()

MONGODB_HOST = env("MONGODB_HOST", "mongo")
MONGODB_PORT = env("MONGODB_PORT", "27017")
MONGODB_USERNAME = env("MONGO_INITDB_ROOT_USERNAME", "")
MONGODB_PASSWORD = env("MONGO_INITDB_ROOT_PASSWORD", "")
MONGODB_URI = env("MONGODB_URI", f"mongodb://{MONGODB_USERNAME}:{MONGODB_PASSWORD}@{MONGODB_HOST}:{MONGODB_PORT}")
MONGODB_NAME = "wind_turbine"
